# Generated by Django 3.1.5 on 2021-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
